Nika2023/News/urls.py
from django.urls import re_path, path, include
from .views import add_news, NewsListView, NewsDetailView, search_news_view, delete_news, NewsViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'news', NewsViewSet, basename='news')
urlpatterns = [
    path('createnews/', add_news, name='new_news'),
    path('', NewsListView.as_view(), name='news'),
    path('news_details/<int:pk>/', NewsDetailView.as_view(), name='news_details'),
    path('search/', search_news_view, name='search_news'),
    path('delete/<int:pk>/', delete_news, name='delete_news'),
    # path('api/v1/newslist/', NewsViewSet.as_view({'get': 'list'})),
    # path('api/v1/newslist/<int:pk>/', NewsViewSet.as_view({'put': 'update'})),
    path('api/v1/', include(router.urls)),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('djoser.urls')), #djoser-auth by tokens
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

Nika2023/Nika2023/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('User/', include('User.urls')),
    #path('News/', include('News.urls')),
    path('News/', include('News.urls')),
    path('', TemplateView.as_view(template_name='base/base.html'), name='home'),
]

if settings.DEBUG:
    import  debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

Nika2023/User/urls.py
from . import views
from .views import register
from django.urls import re_path, path

urlpatterns = [
    path('register/', views.register, name='user_register'),
    path('login/', views.login_view, name='user_login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<slug:username>/', views.profile_view, name='user_profile'),
    path('pass_refresh/', views.change_password, name='pass_refresh'),
    path('update_profile', views.update_profile, name='profile_update')
]

Nika2023/User/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)

    def __str__(self):
        return f'{self.user.first_name+self.user.last_name}'


class UserPhoto(models.Model):
    user = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user_photos/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

Nika2023/User/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, UserPhoto


class UserRegistrationForm(UserCreationForm):
    birth_date = forms.DateField(label='Дата рождения', widget=forms.DateInput(attrs={'type': 'date'}))
    phone_number = forms.CharField(label='Номер телефона')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'birth_date',
                  'phone_number']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'username': 'Имя пользователя',
                  'email': 'Электронная почта', 'password1': 'Придумайте пароль', 'password2': 'Повторите пароль'}


class UserPhotoForm(forms.ModelForm):
    image = forms.ImageField(label='Добавить фото(можно несколько)',
                             widget=forms.ClearableFileInput(attrs={'id': 'id_image', 'multiple': True}),
                             required=False)

    class Meta:
        model = UserPhoto
        exclude = ['uploaded_at', 'user']

Nika2023/User/views.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page

from .forms import UserRegistrationForm, UserPhotoForm
from .models import Profile, UserPhoto
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            birth_date = form.cleaned_data.get('birth_date')
            phone_number = form.cleaned_data.get('phone_number')
            profile = Profile(user=user, birth_date=birth_date, phone_number=phone_number)
            profile.save()
            return redirect('home')
    else:
        form = UserRegistrationForm()
    return render(request, 'User/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = AuthenticationForm(request)
    return render(request, 'User/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return render(request, 'base/base.html')

@cache_page(20)
def profile_view(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    is_own_profile = False
    if user.username == request.user.username:
        is_own_profile = True
        if request.method == 'POST':
            if 'image' in request.FILES:
                form = UserPhotoForm(request.POST, request.FILES)
                if form.is_valid():
                    images = request.FILES.getlist('image')
                    for image in images:
                        UserPhoto.objects.create(user=user, image=image)
                    return redirect('user_profile', username=username)
            else:
                form = UserPhotoForm()
        else:
            form = UserPhotoForm()
    else:
        form = None

    return render(request, 'User/personal_profile.html', {'form': form, 'user': user, 'profile': profile,
                                                          'is_own_profile': is_own_profile})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            # Обновление сессии после изменения пароля
            update_session_auth_hash(request, user)
            messages.success(request, 'Ваш пароль был успешно изменен!')
            return redirect('user_profile', request.user.username)
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме.')
    else:
        form = PasswordChangeForm(user=request.user, label_suffix=': ')
    return render(request, 'User/change_password.html', {'form': form})


@login_required
def update_profile(request):
    if request.method == 'POST':
        # Получение отправленных данных
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone_number = request.POST.get('phone_number')
        # Обновление данных пользователя
        user = request.user
        user.first_name = first_name
        user.last_name = last_name
        user.profile.phone_number = phone_number
        user.save()
        # Возвращение JSON ответа
        return JsonResponse({'success': True})

    # Возвращение ошибки, если запрос не является POST
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

Nika2023/templates/User/change_password.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Изменение пароля</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить пароль</button>
  </form>
{% endblock %}

Nika2023/templates/User/login.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Войти</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
            {% for error in form.username.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            {{ form.password }}
            {% for error in form.password.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="text-danger">{{ error }}</div>
        {% endfor %}
        <button type="submit" class="btn btn-warning text-light">Войти</button>
    </form>
{% endblock %}

Nika2023/templates/User/personal_profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/js.cookie.min.js' %}"></script>
<style>
img.fullscreen {
position: fixed;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
max-width: 90vw;
max-height: 90vh;
z-index: 10000;
cursor: pointer;
}
.slider-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: relative;
  margin-top: 1rem;
}

.slider-nav button {
  background-color: #e8e8e8;
  border: none;
  border-radius: 0.25rem;
  color: #444;
  font-size: 1.3rem;
  outline: none;
  cursor: pointer;
  padding: 0.3rem 0.6rem;
  transition: background-color 0.3s ease-in-out;
}
.slider-nav button:hover {
  background-color: #d4d4d4;
}
.overlay {
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
background-color: rgba(0, 0, 0, 0.8);
display: none;
z-index: 9999;
}

.overlay.show {
display: block;
}

.card-img-top:hover {
    cursor: pointer;
}


</style>
{% endblock %}
{% block title %}Личный кабинет{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Личный кабинет</h1>
    <h2>{{ user.username }}</h2>
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title">Информация о пользователе</h5>
        <p class="card-text">Имя: <span id="first-name">{{ user.first_name }}</span></p>
        <p class="card-text">Фамилия: <span id="last-name">{{ user.last_name }}</span></p>
        <p class="card-text">Дата рождения: <span id="birth-date">{{ profile.birth_date }}</span></p>
        <p class="card-text">Телефон: <span id="phone-number">{{ profile.phone_number }}</span></p>
      </div>
        {% if is_own_profile %}
        <button id="edit-button" class="btn btn-warning text-light">Изменить информацию</button>
        {% endif %}
    </div>
  </div>
{% if is_own_profile %}
<form id="profile-form" style="display: none;" action="{% url 'profile_update' %}">
    {% csrf_token %}
    <input type="text" name="first_name" id="first-name-input" value="{{ user.first_name }}" required>
    <input type="text" name="last_name" id="last-name-input" value="{{ user.last_name }}" required>
    <input type="text" name="phone_number" id="phone-number-input" value="{{ profile.phone_number }}" required>
    <button type="submit" class="btn btn-success">Сохранить</button>
    <button type="button" id="cancel-button" class="btn btn-light">Отмена</button>
</form>
<p id="update-message"></p>
<a class="btn btn-warning text-light" href="{% url 'pass_refresh' %}">Сменить пароль</a>
{% endif %}
<h3>Фотографии</h3>
<div class="slider">
    {% for photo in user.userphoto_set.all %}
    <div class="slide">
        <img class="card-img-top" src="{{ photo.image.url }}" alt="User photo"
             onclick="openFullScreenImage('{{ photo.image.url }}')">
    </div>
    {% endfor %}
</div>
<div class="slider-nav">
    <button class="slick-prev">Предыдущее фото</button>
    <button class="slick-next">Следущее фото</button>
</div>

{% if form %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-warning text-light">Загрузить</button>
</form>
{% endif %}
<script>
function openFullScreenImage(imageUrl) {
// создаем элемент для затемнения страницы
var overlay = document.createElement("div");
overlay.classList.add("overlay");
document.body.appendChild(overlay);

// добавляем класс "show" к элементу overlay
overlay.classList.add("show");

// создаем элемент для отображения изображения
var img = document.createElement("img");
img.setAttribute("src", imageUrl);
img.classList.add("fullscreen");
document.body.appendChild(img);

// закрываем полноэкранный режим при клике на затемненную область или на изображение
overlay.addEventListener("click", closeFullScreenImage);
img.addEventListener("click", closeFullScreenImage);

function closeFullScreenImage() {
overlay.parentNode.removeChild(overlay);
img.parentNode.removeChild(img);
}
}
</script>
<script>
function closeForm() {
  // Показать информацию и скрыть форму
        $('#first-name').show();
        $('#last-name').show();
        $('#birth-date').show();
        $('#phone-number').show();
        $('#profile-form').hide();
}

function openForm() {
        $('#first-name').hide();
        $('#last-name').hide();
        $('#birth-date').hide();
        $('#phone-number').hide();
        $('#profile-form').show();
}

function updateProfileData() {
    var firstName = $('#first-name-input').val();
    var lastName = $('#last-name-input').val();
    var phoneNumber = $('#phone-number-input').val();

    $('#first-name').text(firstName);
    $('#last-name').text(lastName);
    $('#phone-number').text(phoneNumber);
  }

$(document).ready(function() {
    $('.slider').slick({
      dots: false,
      infinite: true,
      speed: 300,
      slidesToShow: 3,
      slidesToScroll: 1,
      appendArrows: $('.slider-nav'),
      prevArrow: $('.slick-prev'),
      nextArrow: $('.slick-next'),
      swipe: false
      });
    $('#edit-button').on('click', openForm);

    // При нажатии на кнопку "Отмена"
    $('#cancel-button').on('click', closeForm);
    $('#profile-form').on('submit', function(e) {
        e.preventDefault(); // Предотвращение отправки формы по умолчанию

        // Получение CSRF-токена из cookie
        var csrftoken = Cookies.get('csrftoken');

        // Получение данных из формы
        var formData = $(this).serialize();

        // Отправка AJAX запроса на сервер
        $.ajax({
            url: $(this).attr('action'),
            type: 'POST',
            data: formData,
            beforeSend: function(xhr, settings) {
                // Добавление CSRF-токена в заголовок запроса
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            },
            success: function(response) {
                if (response.success) {
                    // Вывод сообщения об успешном обновлении данных
                    $('#update-message').text('Данные успешно обновлены');
                    closeForm();
                    updateProfileData();

                } else {
                    // Вывод сообщения об ошибке при обновлении данных
                    $('#update-message').text('Ошибка при обновлении данных');
                }
            },
            error: function() {
                // Вывод сообщения об ошибке при выполнении AJAX запроса
                $('#update-message').text('Ошибка при выполнении запроса');
            }
        });
    });
});
</script>
{% endblock %}

Nika2023/templates/User/register.html
{% extends 'base/base.html' %}
{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    <table>
        {% for field in form %}
            <tr>
                <td>{{field.label}}</td>
                <td>{{ field }}</td>
                {% if field.errors %}
                    <td>
                        <ul class="errorlist">
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        <tr>
            <td colspan="3" align="right">
                <button type="submit" class="btn-warning text-light">Зарегистрироваться</button>
            </td>
        </tr>
    </table>
</form>
{% endblock %}